### PR TITLE
6.4 rel

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by jerpelea** [comment]
@alviteri please test on loire and ganges

**Comment by alviteri** [comment]
I am testing on mermaid since days maybe @oshmoun can test on Loire

**Comment by alviteri** [comment]
kugo mermaid and poplar test ok

**Comment by alviteri** [comment]
updated

**Comment by jerpelea** [comment]
please leave it open until we finish 4.14 stabilization

**Pull request closed without merging**
