### PR TITLE
Qcamera2: Add support for sdm845

### PR DESCRIPTION
**Pull request by alviteri**
Add make file change for sdm845

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
sdm845 does not use this HAL

**Comment by alviteri** [comment]
is it closed source now ?

**Comment by jerpelea** [comment]
The camera for sdm845 is not implemented yet

**Comment by alviteri** [comment]
the only one I found is this but still not 845 in target list

https://source.codeaurora.org/quic/la/platform/hardware/qcom/camera/log/?h=LE.UM.2.3.1.r1.2

**Pull request closed without merging**
