### PR TITLE
Camera: disable open_legacy

### PR DESCRIPTION
**Pull request by alviteri**
The open_legacy check will trigger camera HAL allocating
~67MB of memory. Disable it because sony doesn't need
this feature.

Test: dumpsys meminfo -> check cameraserver memory usage
Bug: 35058355
Change-Id: I722019d432b1533e9427e9a68c290bd27a29afa6

### CODE REVIEW

**Comment by alviteri** [comment]
ping @kholk @humberos @oshmoun to test cam on some third apps and aosp cam ... thanks

Google Camera ok here
Facebook ok here
Whatsapp ok here
Twitter ok here
Shazam ok here
Google Duo ok here

tested oreo ....

**Comment by kholk** [comment]
I can't test right now... Though it looks fine to do that since we are using the correct BSP that implements the new stuff.

**Comment by jerpelea** [comment]
looks ok but has to be tested

**Comment by alviteri** [comment]
Tested open camera API1 AND API2 working here

**Pull request merged**
