### PR TITLE
6.4 test

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
discovery and kugo kernel 4.9 and Pie camera ok

**Comment by rcstar6696** [comment]
OK

Am 03.09.2018 15:24 schrieb "David Viteri" <notifications@github.com>:

poplar kernel 4.4 and Oreo camera ok
discovery and kugo kernel 4.9 and Pie camera ok

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sonyxperiadev/camera/pull/104#issuecomment-418114293>,
or mute the thread

**Comment by jerpelea** [comment]
which camera app?

**Comment by alviteri** [comment]
poplar android 8.1 aosp camera
discovery and kugo android-9.0 open camera

**Comment by alviteri** [comment]
please test or close ... thanks

**Comment by jerpelea** [comment]
leave it open!

**Comment by alviteri** [comment]
latest promotion of qcom camera is ready to be use and all this is included there .... closing here

https://github.com/SonyAosp/platform_hardware_qcom_camera/commits/camera.lnx.3.1.r6-rel

**Pull request closed without merging**
